// Automatically generated by the FlatBuffers compiler. Do not modify.
package hyperionnet

import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.Table
import java.nio.ByteBuffer

@Suppress("unused")
class Clear : Table() {

    fun __init(_i: Int, _bb: ByteBuffer) { __reset(_i, _bb) }

    companion object {
        fun createClear(builder: FlatBufferBuilder, priority: Int): Int {
            builder.startTable(1)
            builder.addInt(0, priority, 0)
            return builder.endTable()
        }
    }
}
