// Automatically generated by the FlatBuffers compiler. Do not modify.
package hyperionnet

import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.Table
import java.nio.ByteBuffer

@Suppress("unused")
class Color : Table() {

    fun __init(_i: Int, _bb: ByteBuffer) { __reset(_i, _bb) }

    companion object {
        fun createColor(builder: FlatBufferBuilder, data: Int, duration: Int): Int {
            builder.startTable(2)
            builder.addInt(1, duration, -1)
            builder.addInt(0, data, -1)
            return builder.endTable()
        }
    }
}
