// Automatically generated by the FlatBuffers compiler. Do not modify.
package hyperionnet

@Suppress("unused")
object Command {
    const val NONE: Byte = 0
    const val Color: Byte = 1
    const val Image: Byte = 2
    const val Clear: Byte = 3
    const val Register: Byte = 4

    fun name(e: Int): String = when (e) {
        NONE.toInt() -> "NONE"
        Color.toInt() -> "Color"
        Image.toInt() -> "Image"
        Clear.toInt() -> "Clear"
        Register.toInt() -> "Register"
        else -> "NONE"
    }
}
