// Automatically generated by the FlatBuffers compiler. Do not modify.
package hyperionnet

import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.Table
import java.nio.ByteBuffer
import java.nio.ByteOrder

@Suppress("unused")
class Image : Table() {

    fun __init(_i: Int, _bb: ByteBuffer) { __reset(_i, _bb) }

    fun __assign(_i: Int, _bb: ByteBuffer): Image { __init(_i, _bb); return this }

    val dataType: Byte
        get() {
            val o = __offset(4)
            return if (o != 0) bb.get(o + bb_pos) else 0
        }

    fun dataAsRawImage(): RawImage? {
        val o = __offset(6)
        return if (o != 0) RawImage().__assign(__indirect(o + bb_pos), bb) else null
    }

    val duration: Int
        get() {
            val o = __offset(8)
            return if (o != 0) bb.getInt(o + bb_pos) else -1
        }

    companion object {
        fun getRootAsImage(bb: ByteBuffer): Image =
            getRootAsImage(bb, Image())

        fun getRootAsImage(bb: ByteBuffer, obj: Image): Image {
            bb.order(ByteOrder.LITTLE_ENDIAN)
            return obj.__assign(bb.getInt(bb.position()) + bb.position(), bb)
        }

        fun createImage(
            builder: FlatBufferBuilder,
            dataType: Byte,
            dataOffset: Int,
            duration: Int = -1
        ): Int {
            builder.startTable(3)
            addDuration(builder, duration)
            addData(builder, dataOffset)
            addDataType(builder, dataType)
            return endImage(builder)
        }

        fun startImage(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addDataType(builder: FlatBufferBuilder, dataType: Byte) = builder.addByte(0, dataType, 0)
        fun addData(builder: FlatBufferBuilder, data: Int) = builder.addOffset(1, data, 0)
        fun addDuration(builder: FlatBufferBuilder, duration: Int) = builder.addInt(2, duration, -1)
        fun endImage(builder: FlatBufferBuilder): Int {
            val o = builder.endTable()
            builder.required(o, 6)  // data is required
            return o
        }
    }
}
