// Automatically generated by the FlatBuffers compiler. Do not modify.
package hyperionnet

@Suppress("unused")
object ImageType {
    const val NONE: Byte = 0
    const val RawImage: Byte = 1
    const val NV12Image: Byte = 2

    fun name(e: Int): String = when (e) {
        NONE.toInt() -> "NONE"
        RawImage.toInt() -> "RawImage"
        NV12Image.toInt() -> "NV12Image"
        else -> "NONE"
    }
}
