// Automatically generated by the FlatBuffers compiler. Do not modify.
package hyperionnet

import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.Table
import java.nio.ByteBuffer
import java.nio.ByteOrder

@Suppress("unused")
class NV12Image : Table() {

    fun __init(_i: Int, _bb: ByteBuffer) { __reset(_i, _bb) }

    fun __assign(_i: Int, _bb: ByteBuffer): NV12Image { __init(_i, _bb); return this }

    val width: Int
        get() {
            val o = __offset(4)
            return if (o != 0) bb.getInt(o + bb_pos) else 0
        }

    val height: Int
        get() {
            val o = __offset(6)
            return if (o != 0) bb.getInt(o + bb_pos) else 0
        }

    companion object {
        fun createNV12Image(
            builder: FlatBufferBuilder,
            dataYOffset: Int,
            dataUvOffset: Int,
            width: Int,
            height: Int,
            strideY: Int = 0,
            strideUv: Int = 0
        ): Int {
            builder.startTable(6)
            builder.addInt(3, height, 0)
            builder.addInt(2, width, 0)
            builder.addOffset(1, dataUvOffset, 0)
            builder.addOffset(0, dataYOffset, 0)
            return builder.endTable()
        }
    }
}
