// Automatically generated by the FlatBuffers compiler. Do not modify.
package hyperionnet

import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.Table
import java.nio.ByteBuffer
import java.nio.ByteOrder

@Suppress("unused")
class RawImage : Table() {

    fun __init(_i: Int, _bb: ByteBuffer) { __reset(_i, _bb) }

    fun __assign(_i: Int, _bb: ByteBuffer): RawImage { __init(_i, _bb); return this }

    val dataLength: Int
        get() {
            val o = __offset(4)
            return if (o != 0) __vector_len(o) else 0
        }

    fun data(j: Int): Byte {
        val o = __offset(4)
        return if (o != 0) bb.get(__vector(o) + j) else 0
    }

    val dataAsByteBuffer: ByteBuffer get() = __vector_as_bytebuffer(4, 1)

    val width: Int
        get() {
            val o = __offset(6)
            return if (o != 0) bb.getInt(o + bb_pos) else -1
        }

    val height: Int
        get() {
            val o = __offset(8)
            return if (o != 0) bb.getInt(o + bb_pos) else -1
        }

    companion object {
        fun getRootAsRawImage(bb: ByteBuffer): RawImage =
            getRootAsRawImage(bb, RawImage())

        fun getRootAsRawImage(bb: ByteBuffer, obj: RawImage): RawImage {
            bb.order(ByteOrder.LITTLE_ENDIAN)
            return obj.__assign(bb.getInt(bb.position()) + bb.position(), bb)
        }

        fun createRawImage(builder: FlatBufferBuilder, dataOffset: Int, width: Int, height: Int): Int {
            builder.startTable(3)
            addHeight(builder, height)
            addWidth(builder, width)
            addData(builder, dataOffset)
            return endRawImage(builder)
        }

        fun startRawImage(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addData(builder: FlatBufferBuilder, data: Int) = builder.addOffset(0, data, 0)
        fun addWidth(builder: FlatBufferBuilder, width: Int) = builder.addInt(1, width, -1)
        fun addHeight(builder: FlatBufferBuilder, height: Int) = builder.addInt(2, height, -1)
        fun endRawImage(builder: FlatBufferBuilder): Int = builder.endTable()
    }
}
