// Automatically generated by the FlatBuffers compiler. Do not modify.
package hyperionnet

import com.google.flatbuffers.Table
import java.nio.ByteBuffer
import java.nio.ByteOrder

@Suppress("unused")
class Reply : Table() {

    fun __init(_i: Int, _bb: ByteBuffer) { __reset(_i, _bb) }

    fun __assign(_i: Int, _bb: ByteBuffer): Reply { __init(_i, _bb); return this }

    val error: String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }

    val video: Int
        get() {
            val o = __offset(6)
            return if (o != 0) bb.getInt(o + bb_pos) else -1
        }

    val registered: Int
        get() {
            val o = __offset(8)
            return if (o != 0) bb.getInt(o + bb_pos) else -1
        }

    companion object {
        fun getRootAsReply(bb: ByteBuffer): Reply =
            getRootAsReply(bb, Reply())

        fun getRootAsReply(bb: ByteBuffer, obj: Reply): Reply {
            bb.order(ByteOrder.LITTLE_ENDIAN)
            return obj.__assign(bb.getInt(bb.position()) + bb.position(), bb)
        }
    }
}
