// Automatically generated by the FlatBuffers compiler. Do not modify.
package hyperionnet

import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.Table
import java.nio.ByteBuffer
import java.nio.ByteOrder

@Suppress("unused")
class Request : Table() {

    fun __init(_i: Int, _bb: ByteBuffer) { __reset(_i, _bb) }

    fun __assign(_i: Int, _bb: ByteBuffer): Request { __init(_i, _bb); return this }

    val commandType: Byte
        get() {
            val o = __offset(4)
            return if (o != 0) bb.get(o + bb_pos) else 0
        }

    fun commandAsRegister(): Register? {
        val o = __offset(6)
        return if (o != 0) Register().__assign(__indirect(o + bb_pos), bb) else null
    }

    fun commandAsImage(): Image? {
        val o = __offset(6)
        return if (o != 0) Image().__assign(__indirect(o + bb_pos), bb) else null
    }

    companion object {
        fun getRootAsRequest(bb: ByteBuffer): Request =
            getRootAsRequest(bb, Request())

        fun getRootAsRequest(bb: ByteBuffer, obj: Request): Request {
            bb.order(ByteOrder.LITTLE_ENDIAN)
            return obj.__assign(bb.getInt(bb.position()) + bb.position(), bb)
        }

        fun createRequest(builder: FlatBufferBuilder, commandType: Byte, commandOffset: Int): Int {
            builder.startTable(2)
            addCommand(builder, commandOffset)
            addCommandType(builder, commandType)
            return endRequest(builder)
        }

        fun startRequest(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addCommandType(builder: FlatBufferBuilder, commandType: Byte) = builder.addByte(0, commandType, 0)
        fun addCommand(builder: FlatBufferBuilder, command: Int) = builder.addOffset(1, command, 0)
        fun endRequest(builder: FlatBufferBuilder): Int {
            val o = builder.endTable()
            builder.required(o, 6)  // command is required
            return o
        }

        fun finishRequestBuffer(builder: FlatBufferBuilder, offset: Int) =
            builder.finish(offset)
    }
}
